seed: 7
cuda: -1 # use cpu is 15% faster
env:
  env_type: pomdp
  env_name: AntBLT-P-v0

  num_eval_tasks: 10 # num of eval episodes

train:
  # 20000*80=1.6M steps, cost 0.5 days
  num_iters: 20000 # number meta-training iterates

eval:
  log_interval: 200 # num of iters
  save_interval: 1000 # not 
  log_tensorboard: true

policy:
  algo_name: a2c
