seed: 7
cuda: -1 # use cpu is 15% faster
env:
  env_type: pomdp
  env_name: HalfCheetahBLT-V-v0

  num_eval_tasks: 10 # num of eval episodes

train:
  # 1000*2048=2M steps, cost 0.5 days
  num_iters: 1000 # number meta-training iterates

eval:
  log_interval: 10 # num of iters
  save_interval: 100 # not 
  log_tensorboard: true

policy:
  algo: ppo
